"""empty message

Revision ID: 26cbdfdc1bdd
Revises: e6d2187c76bf
Create Date: 2022-06-18 15:05:36.385383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cbdfdc1bdd'
down_revision = 'e6d2187c76bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'film', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film', type_='unique')
    # ### end Alembic commands ###
