"""empty message

Revision ID: e6d2187c76bf
Revises: 2b153fff78fc
Create Date: 2022-06-08 09:14:41.040294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d2187c76bf'
down_revision = '2b153fff78fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'poster',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('film', 'poster',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
